import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import NextTopLoader from "nextjs-toploader";
import Client from "./client";

const montserrat = Montserrat({
  subsets: ["latin"],
  weight: "400",
  style: "normal",
  variable: "--font-montserrat",
});

export const metadata: Metadata = {
  title: "SB Repo",
  description: "Generated by create sb app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${montserrat.className} antialiased`}>
        <NextTopLoader />
        <Client>{children}</Client>
      </body>
    </html>
  );
}
